### ISSUE TITLE
More photos of case assembly would be helpful.

### ISSUE THREAD

**Issue by ashepp** [judahpaul16/gpt-home#18]
I ordered the full set of parts but spent longer than I'd anticipated on assembly and still not quite sure I have it right. Could you possibly post some additional photos from other angles? Possibly an assembly video?

**Comment by judahpaul16** [comment]
I can upload some photos here. It was a little tricky. Attach the Sunfounder battery back as the instructions indicate. After that, basically the bottom 2 plates for the Miuzei raspberry pi case are rotated 180deg and sandwich the Sunfounder battery pack. It's rotated to accommodate the battery pack's standoffs:
![20240507_120432](https://github.com/judahpaul16/gpt-home/assets/23343173/3b8917d0-2aff-4e50-b1fd-0bcab05f3619)
![20240507_120403](https://github.com/judahpaul16/gpt-home/assets/23343173/72d8b293-d74a-4f23-87dd-9dc678b4cf46)
![20240507_120348](https://github.com/judahpaul16/gpt-home/assets/23343173/525ef8c0-56a9-4238-9a7c-90d62e4f6f5f)

*Also to ensure full connection of the mini-speaker, I used a Dremel to very slightly shave where the speaker makes contact with the case.*:
![20240507_120452](https://github.com/judahpaul16/gpt-home/assets/23343173/c07f4338-6b74-480d-8872-6bfc0824369e)

**Comment by judahpaul16** [comment]
If you don't want to use a Dremel to shave where the speaker contacts the case you can get one of [these](https://www.amazon.com/gp/product/B016E5PEXC/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1) or rotate the speaker to be upside-down.

**Comment by ashepp** [comment]
Thanks Judah, thats great. Appreciate it!
By the way, I'm trying to run the update you posted this morning and having
issues when trying to run setup.sh.
I'm not super familiar with Raspberry Pi development so not sure if this is
an error on my end or with the script itself.



(env) ***@***.***:~/gpt-home/gpt-home/gpt-home$ chmod +x setup.sh
(env) ***@***.***:~/gpt-home/gpt-home/gpt-home$ ./setup.sh
-bash: ./setup.sh: cannot execute: required file not found
(env) ***@***.***:~/gpt-home/gpt-home/gpt-home$ ls
CONTRIBUTING.md  app.py       functions.py      schematic.fzz  setup.sh
LICENSE          contrib      gpt-web           screenshots
README.md        font5x8.bin  requirements.txt  settings.json
(env) ***@***.***:~/gpt-home/gpt-home/gpt-home$ bash setup.sh
setup.sh: line 2: $'\r': command not found
setup.sh: line 4: syntax error near unexpected token `$'{\r''
'etup.sh: line 4: `check_and_stop_service() {
(env) ***@***.***:~/gpt-home/gpt-home/gpt-home$

**Comment by judahpaul16** [comment]
No problem. Make sure you run the script from your home directory.
```bash
cd ~
sudo rm -rf gpt-home
git clone https://github.com/judahpaul16/gpt-home
sudo chown -R $(whoami):$(whoami) .
sudo chmod -R 755 .
cp gpt-home/contrib/setup.sh ./setup.sh
sudo chmod +x setup.sh
./setup.sh
```

**Comment by ashepp** [comment]
I'll try that. In case it's helpful, chatgpt suggested it might be a
windows / linux issue (I'm using putty on windows 11 to ssh into the
raspberry pi).
BTW, I setup a username of ashepp and a password when installing the
raspberry pi image. I'm prompted for that at login.
I see in the other issues there's a reference to using the default username
/ password. Will I need to change something to make it work?



***@***.***:~/gpt-home$ chmod +x setup.sh ***@***.***:~/gpt-home$
bash setup.sh setup.sh: line 2: $'\r': command not found setup.sh: line 4:
syntax error near unexpected token `$'{\r'' 'etup.sh: line 4:
`check_and_stop_service() { ***@***.***:~/gpt-home$

Pro Search
2 steps completed
Sources
setup.sh
File
·
1
paste.txt
File
·
2
paste-2.txt
File
·
3
[image: s3.amazonaws.com favicon]
[image: s3.amazonaws.com favicon]
View 2 more
Answer
The error messages you're encountering when trying to run the setup.sh script,
specifically "setup.sh: line 2: $'\r': command not found" and "setup.sh:
line 4: syntax error near unexpected token $'{\r''`", indicate that the
script contains Windows-style line endings (CRLF) instead of
Unix/Linux-style line endings (LF). This is a common issue when a script is
edited or created on a Windows system and then transferred to a Unix/Linux
system.To fix this issue, you need to convert the line endings from CRLF to
LF. You can do this using the dos2unix utility, which is specifically
designed for this purpose. Here's how you can do it:

   1. Install dos2unix (if it's not already installed):

   bash
   sudo apt-get updatesudo apt-get install dos2unix

   2. Convert the line endings of the setup.sh script:

   bash
   dos2unix setup.sh

   3. Make the script executable again (just to be sure):

   bash
   chmod +x setup.sh

   4. Run the script:

   bash
   ./setup.sh


This should resolve the syntax errors caused by incorrect line endings and
allow the script to execute properly on your Raspberry Pi.

**Comment by ashepp** [comment]
That worked. thank you!
