### ISSUE TITLE
Troubleshooting OpenWeatherMap

### ISSUE THREAD

**Issue by judahpaul16** [judahpaul16/gpt-home#20]
I've got it working for the basic functionality, Thank you SO much for your help and quick response! 

Now I'm having issues with Open Weather API. Sorry, I'm testing one thing at a time. Please let me know if you want me to start new issues for anything new.

SUCCESS:functions:Heard: "whats the weather in santa fe new mexico"
ERROR:functions:Error: Traceback (most recent call last):
  File "/home/ubuntu/gpt-home/functions.py", line 323, in open_weather_action
    response = await session.get(f"https://api.openweathermap.org/data/3.0/onecall?lat={coords.get('lat')}&lon={coords.get('lon')}&appid={api_key}&units=imperial")
AttributeError: 'NoneType' object has no attribute 'get'

SUCCESS:functions:Something went wrong. 'NoneType' object has no attribute 'get'

_Originally posted by @brainhig in https://github.com/judahpaul16/gpt-home/issues/12#issuecomment-2099039773_

**Comment by judahpaul16** [comment]
Likely caused by coords returning None for the city. Try with the latest commit and let me know. Should handle this more gracefully. See the OpenWeatherMap [city list](https://openweathermap.org/storage/app/media/cities_list.xlsx) for supported cities.

**Comment by brainhig** [comment]
Thanks for the tip. That's exactly the problem... after waiting for the API to become active. It's a pretty limited list of cities that they have data for. 

Thank you again for your responses and assistance!

**Comment by judahpaul16** [comment]
@brainhig No problem. There may be a better way to implement the `coords_from_city()` function to approximate the coordinates or fallback to another API. I've been looking into [Open-Meteo](https://open-meteo.com/) as a potential weather integration as well. Keep an eye out for that.
