### ISSUE TITLE
OpenWeatherAPI Not Functioning

### ISSUE THREAD

**Issue by jlazerus1** [judahpaul16/gpt-home#25]
I have my openweather api key in the web console but when I try to use it, it shows the following error:

<img width="1106" alt="image" src="https://github.com/judahpaul16/gpt-home/assets/85760320/8719ac43-9f2b-4b15-a560-dd990e8342c9">

**Comment by judahpaul16** [comment]
Does the status on the integrations tab show connected? If so does it persist when you refresh?

**Comment by jlazerus1** [comment]
This is what it shows. It does persist when I refresh.

<img width="1169" alt="image" src="https://github.com/judahpaul16/gpt-home/assets/85760320/7158ed48-1f45-43ea-b05f-dba9ae38aea9">

**Comment by judahpaul16** [comment]
> <img alt="image" width="1106" src="https://private-user-images.githubusercontent.com/85760320/329312418-8719ac43-9f2b-4b15-a560-dd990e8342c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNzUzMzUsIm5iZiI6MTcxNTI3NTAzNSwicGF0aCI6Ii84NTc2MDMyMC8zMjkzMTI0MTgtODcxOWFjNDMtOWYyYi00YjE1LWE1NjAtZGQ5OTBlODM0MmM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE3MTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MGNjZmI5Mjk1YTVlZjA1NWRhNmNlNzNkZWE5NmQ5Njk5ZjYxNTM1OWJmNWY3YmI2ZThmZThhZGMyMjExOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ug5yiY1akLVcnM6xxtGkU3x_HbzRNkIFeGPzgEOxfFg">

The error log being cutoff is related to #19. Run `gpt-log` or `tail -n 100 -f /home/$(whoami)/gpt-home/events.log`, ask the same question and you should see the full traceback.

**Comment by jlazerus1** [comment]
INFO:functions:Could not understand audio, waiting for a new phrase...
SUCCESS:functions:Heard: "whats the weather today"
ERROR:functions:Error: Traceback (most recent call last):
  File "/home/ubuntu/gpt-home/functions.py", line 375, in open_weather_action
    raise Exception("No Open Weather API key found. Please enter your API key for Open Weather in the web interface or try reconnecting the service.")
Exception: No Open Weather API key found. Please enter your API key for Open Weather in the web interface or try reconnecting the service.

SUCCESS:functions:Something went wrong. No Open Weather API key found. Please enter your API key for Open Weather in the web interface or try reconnecting the service.

**Comment by judahpaul16** [comment]
Run `gpt-restart` or `sudo systemctl restart gpt-home` and try asking again. If that doesn't work, run the latest setup script, readd your openweather api key in the web interface, and ask again.

```bash
cd ~
wget -O setup.sh https://raw.githubusercontent.com/judahpaul16/gpt-home/main/contrib/setup.sh
sudo chown -R $(whoami):$(whoami) .
sudo chmod -R 755 .
sudo chmod +x setup.sh
./setup.sh
```

**Comment by jlazerus1** [comment]
I re-ran the setup using the latest version and re-entered my api key. I even created a new api key just in case that was an issue but I'm still getting the message below. I do have a subscription to one call 3.0. I also tested the api key successfully in postman.

SUCCESS:functions:Heard: "whats the weather today"
ERROR:functions:Error: Traceback (most recent call last):
  File "/home/ubuntu/gpt-home/functions.py", line 371, in open_weather_action
    raise Exception(f"Received a {response.status} status code. {content.decode()}")
Exception: Received a 401 status code. {"cod":401, "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."}

SUCCESS:functions:Something went wrong. Received a 401 status code. {"cod":401, "message": "Please note that using One Call 3.0 requires a separate subscription to the One Call by Call plan. Learn more here https://openweathermap.org/price. If you have a valid subscription to the One Call by Call plan, but still receive this error, then please see https://openweathermap.org/faq#error401 for more info."}
INFO:functions:Could not understand audio, waiting for a new phrase...

**Comment by judahpaul16** [comment]
Does your [subscriptions](https://home.openweathermap.org/subscriptions) page look like this?

![image](https://github.com/judahpaul16/gpt-home/assets/23343173/5f176c92-97c6-456a-bc5a-485e48534bdd)

**Comment by jlazerus1** [comment]
Yes it does.

**Comment by jlazerus1** [comment]
I actually just got a different response now.

SUCCESS:functions:Heard: "whats the weather today"
ERROR:functions:Error: Traceback (most recent call last):
  File "/home/ubuntu/gpt-home/functions.py", line 362, in open_weather_action
    response = await session.get(f"http://api.openweathermap.org/data/3.0/onecall?lat={coords.get('lat')}&lon={coords.get('lon')}&appid={api_key}&units=imperial")
                                                                                       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

SUCCESS:functions:Something went wrong. 'NoneType' object has no attribute 'get'

**Comment by judahpaul16** [comment]
Hmmm. That should've be handled by 93e866154c9e2f82e13b351e21acac10910df54b but I forgot to implement handling NoneType if city is not found based on IP address. See #20. Patch incoming.

**Comment by judahpaul16** [comment]
@jlazerus1 Pull the latest release and reopen this issue if the problem persists.
