### ISSUE TITLE
Issues using on Google Wifi

### ISSUE THREAD

**Issue by sducksworth** [judahpaul16/gpt-home#53]
System kept reporting "Network not connected. Retrying..." while connected to wifi. Turns out my Google wifi blocks ICMP and there is no way to enable it. 

As a workaround I changed the following in common.py from this:

def network_connected():
    return os.system("ping -c 1 google.com") == 0

to this:

def network_connected():
    return 1

--samd

**Comment by judahpaul16** [comment]
Gotcha. I'll change the method to use the `requests` module. Thanks for reporting.
